name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install PlatformIO
        run: pip install --upgrade platformio
      - name: Build firmware
        run: platformio run
      - name: Run unit tests
        run: |
          g++ -Itests -Iinclude -DCATCH_AMALGAMATED_CUSTOM_MAIN -std=c++17 tests/catch_amalgamated.cpp tests/test_hal.cpp -o test_hal
          ./test_hal --reporter compact
