name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install PlatformIO
        run: pip install --upgrade platformio
      - name: Build firmware
        run: platformio run
      - name: Run unit tests
        run: |
          g++ -Ilib/Catch2 -Itests -Iinclude -DCATCH_AMALGAMATED_CUSTOM_MAIN -std=c++17 \
            lib/Catch2/catch_amalgamated.cpp tests/test_main.cpp \
            tests/MemoryTracker.cpp \
            tests/test_module.cpp tests/test_sensor.cpp tests/test_switch.cpp \
            tests/test_button.cpp tests/test_display.cpp tests/test_digitalpin.cpp \
            tests/test_analogpin.cpp tests/test_oleddisplay.cpp \
            src/Module.cpp src/Sensor.cpp src/Switch.cpp src/Button.cpp src/Display.cpp \
            src/OledDisplay.cpp \
            src/Pin.cpp src/DigitalPin.cpp src/AnalogPin.cpp -o test_all
          ./test_all --reporter compact
