name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  workflow_dispatch:

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.action != 'closed' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha || github.sha }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install PlatformIO
        run: pip install --upgrade platformio
      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y clang-tidy cppcheck gcovr
      - name: Build firmware
        run: platformio run
      - name: Show firmware size
        run: platformio run --target size
      - name: Lint
        run: make lint
      - name: Run unit tests
        run: make test
      - name: Coverage
        run: make coverage
