name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  workflow_dispatch:

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.action != 'closed' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha || github.sha }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install PlatformIO
        run: pip install --upgrade platformio
      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y clang-tidy cppcheck gcovr
      - name: Build firmware
        run: make build

  sanity:
    if: github.event_name != 'pull_request' || github.event.action != 'closed' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha || github.sha }}
      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y cppcheck clang-format
      - name: Check formatting
        run: |
          files=$(git ls-files 'src/*.cpp' 'include/*.hpp' 'tests/*.cpp' 'tests/*.hpp')
          clang-format --dry-run --Werror $files
      - name: Lint
        run: make lint
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            sandbox = false
      - name: Check flake.nix
        run: nix flake show
      - name: Build inside Nix shell
        run: nix develop --option sandbox false --command bash -c "make lint && make build && make test"

  unit-tests:
    if: github.event_name != 'pull_request' || github.event.action != 'closed' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha || github.sha }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install PlatformIO
        run: pip install --upgrade platformio
      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y gcovr
      - name: Run unit tests
        run: make test
      - name: Coverage
        run: make coverage
